<a href="https://colab.research.google.com/github/Semi-Roderick/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [4]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.86610169, 0.90417291, 0.50284719, 0.6790027 ],
       [0.19659994, 0.61218825, 0.66931062, 0.85556245],
       [0.92579445, 0.14752707, 0.56093188, 0.46301537]])

In [7]:
np1.dtype

dtype('float64')

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.1469, -0.9968, -0.4893,  0.5595],
        [ 0.4704, -0.8154, -1.5946, -1.3367],
        [-0.3686, -0.7709, -0.6855, -0.1627]])

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
## create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8661, 0.9042, 0.5028, 0.6790],
        [0.1966, 0.6122, 0.6693, 0.8556],
        [0.9258, 0.1475, 0.5609, 0.4630]], dtype=torch.float64)