<a href="https://colab.research.google.com/github/Semi-Roderick/Pytorch-Tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [6]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [7]:
# or you can do this to add
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
#sub
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [9]:
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

In [10]:
# mul
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [11]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [12]:
# div
tensor_a/tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [14]:
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [15]:
# remainder longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [16]:
#exponents/power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [17]:
#another way to write longhand
tensor_a.add(tensor_b)


tensor([ 6,  8, 10, 12])

In [21]:
#reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [20]:
tensor_a

tensor([1, 2, 3, 4])

In [25]:
#tensor_a = tensor_a+tensor_b
tensor_a.add_(tensor_b)


tensor([21, 26, 31, 36])

In [26]:
tensor_a

tensor([21, 26, 31, 36])